services:
    postgres:
        image: postgres:13
        ports:
            - "5800:5432"
        environment:
            POSTGRES_DB: eateazedatabase
            POSTGRES_USER: eateaze-app
            POSTGRES_PASSWORD: Ml37RemA7hEGjI

        